name: iosApp
options:
  bundleIdPrefix: com.kozyrevda
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  iosApp:
    type: application
    platform: iOS
    sources: [iosApp]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kozyrevda.menstrualcalendar
        INFOPLIST_FILE: iosApp/Info.plist
        FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        OTHER_LDFLAGS: "$(inherited) -framework ComposeApp"
    preBuildScripts:
      - name: Compile Kotlin Framework
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
